// <auto-generated />
using System;
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(BewerberDbContext))]
    partial class BewerberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp1.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BewerberId")
                        .HasColumnType("int");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strasse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresseId");

                    b.HasIndex("BewerberId");

                    b.ToTable("AdresseSet");
                });

            modelBuilder.Entity("ConsoleApp1.Ausschreibung", b =>
                {
                    b.Property<int>("AusschreibungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Einstellungsdatum")
                        .HasColumnType("datetime2");

                    b.HasKey("AusschreibungId");

                    b.ToTable("AusschreibungSet");
                });

            modelBuilder.Entity("ConsoleApp1.AusschreibungBewerber", b =>
                {
                    b.Property<int>("AusschreibungBewerberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AusschreibungId")
                        .HasColumnType("int");

                    b.Property<int>("BewerberId")
                        .HasColumnType("int");

                    b.HasKey("AusschreibungBewerberId");

                    b.HasIndex("AusschreibungId");

                    b.HasIndex("BewerberId");

                    b.ToTable("AusschreibungBewerberSet");
                });

            modelBuilder.Entity("ConsoleApp1.Bewerber", b =>
                {
                    b.Property<int>("BewerberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BewerberId");

                    b.ToTable("BewerberSet");
                });

            modelBuilder.Entity("ConsoleApp1.Adresse", b =>
                {
                    b.HasOne("ConsoleApp1.Bewerber", "Bewerber")
                        .WithMany()
                        .HasForeignKey("BewerberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.AusschreibungBewerber", b =>
                {
                    b.HasOne("ConsoleApp1.Ausschreibung", "Ausschreibung")
                        .WithMany("AusschreibungenBewerber")
                        .HasForeignKey("AusschreibungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Bewerber", "Bewerber")
                        .WithMany("AusschreibungenBewerber")
                        .HasForeignKey("BewerberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
